
(define input (list

(cons "dark olive" (list (cons 2 "muted brown") (cons 1 "mirrored tomato") (cons 4 "bright black")))
(cons "faded coral" (list (cons 3 "drab cyan") (cons 1 "light aqua")))
(cons "plaid plum" (list (cons 2 "mirrored cyan")))
(cons "clear maroon" (list (cons 1 "dotted turquoise") (cons 3 "dim lavender")))
(cons "plaid coral" (list (cons 3 "posh fuchsia") (cons 3 "dotted beige") (cons 2 "wavy turquoise")))
(cons "mirrored indigo" (list (cons 5 "pale orange") (cons 5 "striped aqua") (cons 1 "dotted cyan") (cons 4 "muted coral")))
(cons "striped brown" (list (cons 4 "faded green") (cons 5 "vibrant red") (cons 3 "drab black") (cons 3 "dark orange")))
(cons "drab fuchsia" (list (cons 5 "shiny chartreuse") (cons 1 "dark orange") (cons 4 "drab blue") (cons 1 "bright chartreuse")))
(cons "light fuchsia" (list (cons 3 "bright gold") (cons 5 "clear indigo")))
(cons "plaid olive" (list (cons 4 "striped indigo") (cons 4 "muted olive") (cons 2 "light gray") (cons 2 "wavy purple")))
(cons "dotted green" (list (cons 2 "faded yellow")))
(cons "dotted cyan" (list (cons 1 "light red") (cons 5 "dark cyan")))
(cons "muted magenta" (list (cons 2 "clear plum")))
(cons "mirrored cyan" (list (cons 4 "bright lavender") (cons 3 "mirrored gold") (cons 2 "plaid silver") (cons 1 "posh chartreuse")))
(cons "muted red" (list (cons 2 "wavy olive") (cons 4 "shiny cyan")))
(cons "clear indigo" (list (cons 2 "dotted magenta") (cons 4 "bright silver") (cons 4 "muted aqua")))
(cons "plaid chartreuse" (list (cons 3 "dark chartreuse") (cons 1 "faded lavender")))
(cons "wavy tan" (list (cons 3 "light red")))
(cons "bright crimson" (list (cons 4 "pale magenta")))
(cons "pale yellow" (list (cons 3 "clear plum") (cons 2 "vibrant cyan") (cons 2 "muted white")))
(cons "pale tomato" (list (cons 2 "muted red")))
(cons "dull salmon" (list (cons 3 "dark gold")))
(cons "light white" (list (cons 2 "drab chartreuse")))
(cons "drab plum" (list (cons 1 "dark brown")))
(cons "shiny purple" (list (cons 3 "pale brown") (cons 1 "bright crimson") (cons 5 "muted teal")))
(cons "pale red" (list (cons 5 "posh cyan") (cons 2 "drab cyan")))
(cons "dull bronze" (list (cons 2 "striped indigo") (cons 4 "plaid black") (cons 3 "clear violet") (cons 1 "dull chartreuse")))
(cons "wavy indigo" (list (cons 2 "dull coral") (cons 1 "dark tan")))
(cons "vibrant silver" (list (cons 5 "muted aqua")))
(cons "shiny tan" (list (cons 4 "pale beige") (cons 4 "bright gold") (cons 5 "muted coral") (cons 3 "shiny red")))
(cons "dim yellow" (list (cons 1 "dotted chartreuse")))
(cons "faded white" (list (cons 5 "posh lavender") (cons 3 "bright silver") (cons 2 "dark green") (cons 5 "muted lavender")))
(cons "shiny tomato" (list (cons 4 "mirrored chartreuse") (cons 2 "bright yellow") (cons 4 "vibrant plum")))
(cons "dark yellow" (list (cons 3 "plaid lime") (cons 4 "wavy lavender")))
(cons "dim magenta" (list (cons 3 "wavy violet")))
(cons "striped white" (list (cons 5 "striped chartreuse")))
(cons "muted gray" (list (cons 5 "muted brown") (cons 5 "light lavender") (cons 2 "clear gold") (cons 1 "shiny green")))
(cons "drab white" (list (cons 4 "muted yellow") (cons 3 "posh lavender") (cons 3 "faded fuchsia")))
(cons "dark lime" (list (cons 1 "bright crimson")))
(cons "muted salmon" (list (cons 4 "dull red") (cons 1 "dull violet")))
(cons "muted black" (list (cons 2 "vibrant black") (cons 5 "pale tomato")))
(cons "plaid white" (list (cons 4 "drab black") (cons 4 "drab cyan") (cons 1 "dim olive")))
(cons "clear green" (list (cons 3 "wavy purple") (cons 1 "pale gold")))
(cons "drab orange" (list (cons 4 "clear maroon") (cons 3 "vibrant gold")))
(cons "light salmon" (list (cons 1 "pale black") (cons 2 "posh fuchsia")))
(cons "faded tomato" (list (cons 5 "faded black") (cons 3 "vibrant coral") (cons 3 "bright brown")))
(cons "dull green" (list (cons 5 "clear lime")))
(cons "dim orange" (list (cons 5 "posh red") (cons 2 "dim gray") (cons 2 "muted gold")))
(cons "dotted orange" (list (cons 1 "faded tan") (cons 2 "drab tomato")))
(cons "dull gold" (list (cons 5 "muted gold")))
(cons "clear beige" (list (cons 5 "plaid tan") (cons 4 "dim maroon")))
(cons "mirrored bronze" (list (cons 1 "clear blue") (cons 2 "clear tan") (cons 3 "clear orange")))
(cons "shiny brown" (list (cons 5 "light tomato")))
(cons "pale cyan" (list (cons 3 "dull silver")))
(cons "muted purple" (list (cons 4 "posh brown")))
(cons "pale maroon" (list (cons 1 "clear maroon") (cons 5 "vibrant yellow") (cons 1 "shiny violet")))
(cons "muted green" (list (cons 5 "plaid plum")))
(cons "light coral" (list (cons 5 "bright lime") (cons 1 "dotted indigo") (cons 5 "shiny bronze")))
(cons "wavy beige" (list (cons 5 "light magenta") (cons 3 "pale lime") (cons 1 "faded yellow")))
(cons "wavy turquoise" (list (cons 5 "shiny red") (cons 3 "mirrored yellow") (cons 2 "posh bronze")))
(cons "pale brown" (list (cons 2 "striped salmon") (cons 4 "vibrant plum") (cons 2 "dull silver")))
(cons "striped bronze" (list (cons 3 "posh black") (cons 2 "bright yellow") (cons 3 "dotted silver") (cons 1 "mirrored violet")))
(cons "pale tan" (list (cons 4 "shiny lavender") (cons 3 "dotted turquoise") (cons 3 "pale turquoise") (cons 5 "plaid white")))
(cons "muted crimson" (list (cons 4 "dull lime") (cons 4 "pale magenta") (cons 2 "light cyan")))
(cons "dotted purple" (list (cons 2 "wavy magenta")))
(cons "dull black" (list (cons 3 "light crimson") (cons 3 "mirrored fuchsia") (cons 3 "posh lime")))
(cons "mirrored aqua" (list (cons 1 "dark brown") (cons 5 "pale gold") (cons 2 "pale purple") (cons 2 "vibrant crimson")))
(cons "shiny beige" (list (cons 2 "muted indigo") (cons 2 "dark tan")))
(cons "shiny aqua" (list (cons 5 "vibrant tan") (cons 2 "pale tomato") (cons 2 "faded blue") (cons 4 "pale magenta")))
(cons "mirrored lavender" (list (cons 4 "faded yellow") (cons 3 "light chartreuse") (cons 2 "dull crimson") (cons 1 "pale aqua")))
(cons "faded gray" (list (cons 5 "bright yellow") (cons 4 "light silver")))
(cons "light tan" (list (cons 3 "bright fuchsia") (cons 3 "light crimson") (cons 3 "clear olive") (cons 1 "clear silver")))
(cons "dull crimson" (list (cons 3 "wavy olive") (cons 1 "light maroon")))
(cons "pale olive" (list (cons 4 "vibrant purple") (cons 3 "clear fuchsia") (cons 2 "pale tan")))
(cons "dim beige" (list (cons 3 "dull silver")))
(cons "dark bronze" (list (cons 1 "mirrored orange") (cons 2 "wavy crimson") (cons 1 "dark maroon")))
(cons "mirrored fuchsia" (list (cons 1 "dark chartreuse") (cons 1 "dotted bronze") (cons 5 "shiny silver")))
(cons "striped tomato" (list (cons 1 "dark fuchsia") (cons 5 "vibrant maroon") (cons 4 "drab crimson")))
(cons "muted chartreuse" (list (cons 1 "light tomato") (cons 3 "light magenta") (cons 3 "dull beige")))
(cons "muted violet" (list (cons 5 "light tomato")))
(cons "dim violet" (list (cons 2 "mirrored purple") (cons 3 "bright black") (cons 5 "vibrant plum")))
(cons "muted beige" (list (cons 4 "muted plum") (cons 4 "mirrored gold") (cons 5 "bright yellow")))
(cons "shiny coral" (list (cons 5 "vibrant gray") (cons 1 "light bronze") (cons 5 "faded chartreuse") (cons 2 "plaid violet")))
(cons "dotted yellow" (list (cons 5 "dotted turquoise")))
(cons "faded bronze" (list (cons 4 "dull purple") (cons 2 "pale fuchsia")))
(cons "clear fuchsia" (list (cons 5 "bright yellow")))
(cons "dotted beige" (list (cons 1 "pale turquoise")))
(cons "bright aqua" (list (cons 2 "faded silver") (cons 5 "dim fuchsia")))
(cons "dim silver" (list (cons 5 "wavy brown") (cons 1 "light maroon") (cons 2 "wavy black")))
(cons "plaid tan" (list (cons 3 "dotted green")))
(cons "drab teal" (list (cons 4 "mirrored violet") (cons 5 "dotted bronze") (cons 1 "pale cyan")))
(cons "plaid yellow" (list (cons 5 "shiny magenta") (cons 1 "dark silver") (cons 5 "shiny indigo") (cons 3 "faded gray")))
(cons "dull cyan" (list (cons 1 "posh plum") (cons 5 "dim coral")))
(cons "pale beige" (list (cons 3 "dark cyan") (cons 4 "faded tan") (cons 2 "plaid silver")))
(cons "faded salmon" (list (cons 2 "light olive") (cons 2 "dark tan")))
(cons "bright silver" (list (cons 1 "clear fuchsia") (cons 2 "clear lime")))
(cons "dark lavender" (list (cons 1 "pale cyan") (cons 5 "dotted salmon") (cons 1 "striped turquoise") (cons 2 "dim crimson")))
(cons "light gray" (list (cons 3 "dotted chartreuse") (cons 3 "dull red") (cons 4 "bright gold") (cons 2 "light lime")))
(cons "dark indigo" (list (cons 5 "shiny coral") (cons 1 "muted teal") (cons 2 "plaid purple") (cons 4 "faded yellow")))
(cons "light maroon" (list (cons 1 "wavy brown")))
(cons "dotted brown" (list (cons 1 "clear violet")))
(cons "pale indigo" (list (cons 1 "wavy brown") (cons 2 "dark olive") (cons 4 "pale black") (cons 5 "striped lavender")))
(cons "pale purple" (list (cons 5 "bright chartreuse") (cons 1 "vibrant magenta") (cons 4 "clear tomato") (cons 4 "light cyan")))
(cons "dim teal" (list (cons 2 "dark salmon") (cons 5 "mirrored gold") (cons 3 "bright gold")))
(cons "wavy olive" (list (cons 1 "vibrant purple") (cons 3 "dull silver")))
(cons "pale aqua" (list (cons 4 "dark violet") (cons 2 "dark plum") (cons 3 "vibrant brown")))
(cons "muted cyan" (list (cons 5 "vibrant crimson") (cons 3 "pale magenta")))
(cons "vibrant fuchsia" (list (cons 2 "light beige") (cons 5 "bright purple") (cons 3 "light maroon") (cons 4 "dull beige")))
(cons "bright blue" (list (cons 4 "vibrant plum")))
(cons "vibrant green" (list (cons 1 "dark salmon")))
(cons "dull red" (list (cons 2 "dotted maroon") (cons 1 "posh salmon") (cons 3 "dotted chartreuse") (cons 2 "dim yellow")))
(cons "dotted magenta" (list (cons 3 "plaid violet") (cons 3 "light gray")))
(cons "wavy bronze" (list (cons 1 "posh plum") (cons 2 "bright lavender")))
(cons "shiny orange" (list (cons 3 "muted plum")))
(cons "plaid bronze" (list (cons 5 "plaid chartreuse") (cons 3 "mirrored turquoise") (cons 3 "light salmon")))
(cons "shiny yellow" (list (cons 4 "striped teal") (cons 1 "vibrant maroon") (cons 1 "drab indigo") (cons 4 "muted beige")))
(cons "faded indigo" (list (cons 2 "posh lime") (cons 1 "vibrant teal")))
(cons "posh tomato" (list (cons 4 "striped salmon") (cons 3 "drab red")))
(cons "light plum" (list (cons 3 "bright blue") (cons 5 "dotted black") (cons 4 "shiny brown") (cons 2 "clear tan")))
(cons "pale green" (list (cons 4 "clear maroon") (cons 4 "dull green") (cons 5 "clear aqua") (cons 3 "drab beige")))
(cons "drab brown" (list (cons 1 "bright plum") (cons 5 "striped indigo") (cons 1 "vibrant lime")))
(cons "muted lime" (list (cons 3 "faded tan") (cons 5 "vibrant magenta") (cons 5 "posh coral")))
(cons "faded violet" (list (cons 1 "posh purple") (cons 4 "muted crimson") (cons 5 "striped red")))
(cons "striped green" (list (cons 4 "clear chartreuse") (cons 4 "dim maroon") (cons 1 "faded cyan") (cons 5 "faded silver")))
(cons "dim plum" (list (cons 1 "faded tan") (cons 5 "vibrant crimson") (cons 3 "light gray") (cons 2 "wavy teal")))
(cons "drab cyan" (list (cons 4 "muted plum") (cons 5 "mirrored black") (cons 4 "clear fuchsia")))
(cons "vibrant lime" (list (cons 2 "pale brown") (cons 5 "plaid violet")))
(cons "drab purple" (list (cons 1 "posh turquoise") (cons 4 "clear violet") (cons 5 "faded coral") (cons 1 "striped gold")))
(cons "mirrored gray" (list (cons 3 "dotted orange") (cons 4 "mirrored tomato") (cons 4 "plaid lime")))
(cons "plaid teal" (list (cons 2 "dim coral") (cons 5 "shiny magenta") (cons 5 "striped beige")))
(cons "vibrant white" (list (cons 2 "shiny red") (cons 1 "plaid black")))
(cons "faded crimson" (list (cons 2 "faded yellow")))
(cons "dim chartreuse" (list (cons 4 "mirrored teal") (cons 5 "light lavender")))
(cons "wavy magenta" (list (cons 3 "dark cyan")))
(cons "mirrored magenta" (list (cons 4 "muted salmon") (cons 4 "pale maroon")))
(cons "plaid silver" (list (cons 2 "pale turquoise") (cons 3 "posh salmon")))
(cons "bright cyan" (list (cons 3 "dark orange") (cons 1 "mirrored gold") (cons 1 "light violet") (cons 5 "faded silver")))
(cons "faded orange" (list (cons 3 "drab red") (cons 5 "dark tan") (cons 2 "vibrant magenta")))
(cons "wavy gold" (list (cons 4 "drab tomato") (cons 2 "muted yellow")))
(cons "wavy salmon" (list (cons 2 "dotted bronze") (cons 3 "light white") (cons 2 "dotted brown")))
(cons "posh plum" (list (cons 4 "drab black") (cons 1 "light silver")))
(cons "dim aqua" (list (cons 5 "striped black") (cons 1 "bright yellow") (cons 4 "posh salmon") (cons 3 "striped salmon")))
(cons "shiny fuchsia" (list (cons 2 "dim cyan")))
(cons "dark tan" (list (cons 3 "dull plum")))
(cons "mirrored red" (list (cons 3 "pale lime") (cons 3 "dim maroon")))
(cons "bright purple" (list (cons 4 "posh magenta") (cons 4 "wavy magenta") (cons 3 "posh plum") (cons 3 "dull lime")))
(cons "striped olive" (list (cons 3 "bright lavender") (cons 3 "mirrored black") (cons 3 "bright gold") (cons 2 "pale plum")))
(cons "dotted bronze" (list (cons 3 "dull coral") (cons 1 "faded black")))
(cons "shiny green" (list (cons 1 "shiny indigo")))
(cons "mirrored chartreuse" '())
(cons "pale crimson" (list (cons 2 "light orange") (cons 3 "light lime") (cons 4 "dotted cyan")))
(cons "shiny lavender" (list (cons 5 "shiny crimson") (cons 5 "striped tan")))
(cons "wavy blue" (list (cons 1 "pale brown") (cons 2 "light cyan") (cons 1 "light magenta") (cons 4 "pale tan")))
(cons "muted plum" (list (cons 4 "dull red") (cons 1 "dotted maroon") (cons 1 "vibrant red") (cons 4 "bright chartreuse")))
(cons "vibrant violet" (list (cons 4 "dull brown")))
(cons "faded chartreuse" (list (cons 3 "dotted yellow")))
(cons "drab chartreuse" (list (cons 4 "shiny gold")))
(cons "posh crimson" (list (cons 3 "clear cyan") (cons 2 "light crimson") (cons 1 "drab crimson") (cons 5 "clear blue")))
(cons "drab tomato" (list (cons 4 "striped salmon")))
(cons "clear red" (list (cons 1 "pale blue") (cons 1 "posh orange") (cons 2 "dark aqua") (cons 5 "posh red")))
(cons "drab lavender" (list (cons 2 "muted gray")))
(cons "pale blue" (list (cons 5 "pale beige") (cons 3 "muted green") (cons 3 "shiny white")))
(cons "posh cyan" (list (cons 2 "clear aqua") (cons 2 "drab chartreuse") (cons 2 "dark purple") (cons 2 "posh salmon")))
(cons "faded silver" (list (cons 5 "dim salmon") (cons 2 "striped bronze")))
(cons "dim green" (list (cons 1 "dark fuchsia")))
(cons "plaid aqua" (list (cons 3 "dim red") (cons 3 "drab turquoise") (cons 3 "dim aqua") (cons 5 "dull salmon")))
(cons "posh fuchsia" (list (cons 2 "dotted fuchsia")))
(cons "striped lime" (list (cons 1 "dull silver") (cons 5 "posh black") (cons 1 "dark fuchsia") (cons 3 "dull lime")))
(cons "clear olive" (list (cons 1 "pale crimson") (cons 2 "shiny orange") (cons 2 "posh magenta") (cons 1 "dark fuchsia")))
(cons "bright lime" (list (cons 2 "striped tan") (cons 5 "dull plum") (cons 4 "bright yellow")))
(cons "faded green" (list (cons 2 "pale turquoise") (cons 5 "light lime")))
(cons "plaid indigo" (list (cons 1 "drab crimson")))
(cons "shiny turquoise" (list (cons 2 "faded crimson")))
(cons "drab aqua" (list (cons 4 "mirrored red") (cons 1 "drab gold") (cons 5 "wavy orange")))
(cons "dim gray" (list (cons 1 "shiny lime") (cons 5 "dotted fuchsia")))
(cons "light teal" (list (cons 5 "pale beige") (cons 4 "shiny cyan") (cons 2 "striped red") (cons 1 "light orange")))
(cons "wavy red" (list (cons 3 "dotted tan") (cons 3 "pale aqua")))
(cons "vibrant red" '())
(cons "striped salmon" '())
(cons "clear silver" (list (cons 1 "shiny orange") (cons 1 "pale aqua") (cons 1 "faded purple") (cons 2 "dim coral")))
(cons "muted tan" (list (cons 3 "pale maroon") (cons 4 "dotted maroon") (cons 2 "bright plum") (cons 4 "pale teal")))
(cons "faded yellow" (list (cons 2 "striped black") (cons 2 "dotted chartreuse") (cons 5 "drab chartreuse") (cons 5 "shiny tomato")))
(cons "dark green" (list (cons 1 "light lime")))
(cons "striped cyan" (list (cons 2 "posh magenta") (cons 2 "dim cyan")))
(cons "vibrant teal" (list (cons 2 "dim magenta") (cons 1 "bright chartreuse") (cons 5 "bright tan") (cons 1 "bright yellow")))
(cons "bright red" (list (cons 1 "posh white")))
(cons "bright magenta" (list (cons 3 "posh salmon") (cons 2 "dull fuchsia") (cons 1 "posh lavender")))
(cons "bright white" (list (cons 1 "bright chartreuse") (cons 1 "mirrored yellow")))
(cons "dotted teal" (list (cons 3 "bright gray") (cons 3 "vibrant fuchsia")))
(cons "clear blue" (list (cons 4 "pale brown") (cons 2 "drab indigo") (cons 2 "pale salmon") (cons 3 "muted olive")))
(cons "dull brown" (list (cons 1 "dim cyan") (cons 2 "vibrant plum") (cons 3 "posh chartreuse")))
(cons "vibrant tan" (list (cons 1 "dark orange")))
(cons "shiny white" (list (cons 3 "mirrored violet") (cons 1 "drab indigo")))
(cons "clear violet" (list (cons 2 "vibrant crimson") (cons 1 "light gold") (cons 2 "striped silver")))
(cons "bright coral" (list (cons 3 "drab blue") (cons 4 "muted olive") (cons 3 "faded purple") (cons 1 "vibrant maroon")))
(cons "dotted aqua" (list (cons 5 "wavy black") (cons 4 "mirrored gold") (cons 1 "posh red") (cons 2 "plaid silver")))
(cons "clear crimson" (list (cons 1 "plaid gold")))
(cons "faded fuchsia" (list (cons 5 "shiny coral") (cons 2 "pale beige")))
(cons "wavy crimson" (list (cons 4 "dotted turquoise") (cons 1 "light gray") (cons 5 "wavy purple") (cons 1 "faded gray")))
(cons "dark fuchsia" (list (cons 2 "wavy brown") (cons 3 "vibrant orange")))
(cons "striped plum" (list (cons 1 "vibrant cyan") (cons 3 "posh lime")))
(cons "shiny salmon" (list (cons 5 "drab magenta") (cons 4 "mirrored turquoise")))
(cons "dim brown" (list (cons 2 "shiny gold") (cons 5 "dotted cyan") (cons 3 "plaid cyan")))
(cons "posh violet" (list (cons 3 "dim red") (cons 2 "posh white") (cons 3 "faded aqua") (cons 4 "shiny gold")))
(cons "pale black" (list (cons 3 "pale plum")))
(cons "shiny red" (list (cons 4 "posh salmon") (cons 1 "dotted chartreuse")))
(cons "dull olive" (list (cons 2 "light blue")))
(cons "bright olive" (list (cons 2 "striped olive") (cons 3 "muted plum") (cons 2 "striped magenta")))
(cons "posh brown" (list (cons 1 "vibrant gold") (cons 2 "wavy silver") (cons 4 "dotted salmon") (cons 4 "drab orange")))
(cons "bright tan" (list (cons 3 "light chartreuse")))
(cons "dull beige" (list (cons 2 "pale violet")))
(cons "light yellow" (list (cons 2 "clear indigo") (cons 2 "wavy brown") (cons 2 "bright black") (cons 4 "shiny lime")))
(cons "dull aqua" (list (cons 2 "dull black") (cons 5 "posh black") (cons 2 "wavy fuchsia")))
(cons "dark gold" (list (cons 3 "clear fuchsia") (cons 1 "dark cyan") (cons 4 "dark orange")))
(cons "wavy white" (list (cons 2 "dark brown") (cons 5 "drab yellow") (cons 5 "dotted turquoise") (cons 4 "muted tomato")))
(cons "posh silver" (list (cons 2 "dim chartreuse") (cons 5 "light fuchsia") (cons 4 "faded purple") (cons 5 "drab cyan")))
(cons "dotted coral" (list (cons 5 "plaid silver") (cons 2 "posh beige") (cons 5 "dim beige") (cons 2 "vibrant crimson")))
(cons "drab silver" (list (cons 1 "posh chartreuse")))
(cons "dull teal" (list (cons 1 "dim indigo")))
(cons "wavy brown" '())
(cons "posh purple" (list (cons 1 "wavy purple") (cons 5 "muted gold")))
(cons "faded magenta" (list (cons 2 "wavy aqua") (cons 4 "vibrant beige")))
(cons "vibrant magenta" (list (cons 5 "wavy black") (cons 4 "shiny maroon") (cons 3 "dim tomato") (cons 5 "vibrant gray")))
(cons "mirrored brown" (list (cons 2 "light aqua") (cons 1 "clear orange") (cons 2 "bright lavender")))
(cons "light crimson" (list (cons 5 "posh chartreuse")))
(cons "dotted olive" (list (cons 5 "dim tomato") (cons 3 "dim plum")))
(cons "light indigo" (list (cons 1 "bright gold") (cons 4 "drab chartreuse") (cons 4 "dim fuchsia") (cons 3 "vibrant black")))
(cons "vibrant chartreuse" (list (cons 5 "dim crimson") (cons 1 "clear plum") (cons 4 "striped black")))
(cons "pale violet" (list (cons 3 "dark salmon")))
(cons "bright violet" (list (cons 3 "striped aqua")))
(cons "dull maroon" (list (cons 1 "drab aqua") (cons 3 "mirrored lavender") (cons 5 "dotted brown")))
(cons "dim lime" (list (cons 3 "wavy salmon") (cons 3 "striped tan")))
(cons "dotted tan" (list (cons 3 "dull yellow") (cons 3 "shiny violet")))
(cons "posh yellow" (list (cons 3 "dull crimson") (cons 4 "dim olive") (cons 4 "dark black")))
(cons "dull violet" (list (cons 4 "bright yellow") (cons 2 "posh magenta") (cons 5 "shiny red")))
(cons "dotted silver" (list (cons 2 "wavy turquoise") (cons 3 "dull tomato") (cons 3 "bright tan") (cons 1 "dotted salmon")))
(cons "pale gray" (list (cons 1 "plaid turquoise") (cons 4 "bright salmon")))
(cons "clear purple" (list (cons 5 "shiny gold") (cons 5 "faded teal")))
(cons "striped tan" (list (cons 1 "mirrored cyan") (cons 2 "pale beige")))
(cons "dotted indigo" (list (cons 2 "pale purple") (cons 2 "pale black") (cons 2 "dark salmon")))
(cons "clear turquoise" (list (cons 2 "light lavender")))
(cons "wavy plum" (list (cons 5 "shiny aqua")))
(cons "muted indigo" (list (cons 5 "drab teal")))
(cons "muted yellow" (list (cons 2 "vibrant cyan") (cons 1 "dim white")))
(cons "dark white" (list (cons 2 "drab crimson") (cons 5 "dull gray")))
(cons "faded blue" (list (cons 1 "faded olive") (cons 2 "shiny magenta") (cons 5 "dark plum")))
(cons "posh tan" (list (cons 2 "posh plum") (cons 5 "muted black") (cons 3 "clear indigo") (cons 4 "striped gold")))
(cons "striped silver" (list (cons 4 "drab tomato")))
(cons "muted lavender" (list (cons 3 "dim silver") (cons 2 "wavy lavender") (cons 1 "faded tan")))
(cons "wavy chartreuse" (list (cons 5 "dull bronze")))
(cons "dark blue" (list (cons 1 "dotted silver") (cons 3 "light yellow") (cons 3 "mirrored bronze") (cons 4 "shiny lavender")))
(cons "dim turquoise" (list (cons 3 "pale green") (cons 4 "mirrored gray")))
(cons "muted blue" (list (cons 1 "striped lavender") (cons 3 "dark fuchsia")))
(cons "faded brown" (list (cons 2 "dotted violet") (cons 5 "faded indigo") (cons 5 "drab indigo")))
(cons "shiny magenta" (list (cons 5 "dotted turquoise") (cons 3 "plaid violet") (cons 2 "dim cyan")))
(cons "clear chartreuse" (list (cons 3 "pale maroon") (cons 5 "plaid blue") (cons 1 "clear tan")))
(cons "faded turquoise" (list (cons 4 "mirrored magenta")))
(cons "posh turquoise" (list (cons 3 "dotted yellow") (cons 5 "striped purple") (cons 3 "pale cyan")))
(cons "vibrant tomato" (list (cons 4 "dark cyan")))
(cons "mirrored white" (list (cons 2 "mirrored indigo") (cons 3 "dim cyan") (cons 3 "bright lavender")))
(cons "dull purple" (list (cons 2 "striped yellow") (cons 3 "dull plum") (cons 3 "shiny gold") (cons 3 "pale gold")))
(cons "mirrored yellow" (list (cons 4 "shiny crimson")))
(cons "posh white" (list (cons 3 "mirrored orange")))
(cons "wavy fuchsia" (list (cons 3 "dotted tan") (cons 5 "shiny coral")))
(cons "mirrored green" (list (cons 1 "dull white") (cons 5 "shiny crimson")))
(cons "plaid turquoise" (list (cons 2 "pale salmon") (cons 4 "dull beige")))
(cons "clear cyan" (list (cons 1 "dim silver") (cons 4 "drab chartreuse")))
(cons "mirrored purple" (list (cons 1 "dull coral") (cons 3 "vibrant plum")))
(cons "dim lavender" (list (cons 1 "striped black") (cons 4 "shiny red") (cons 4 "posh chartreuse") (cons 2 "dim teal")))
(cons "plaid cyan" (list (cons 1 "dim orange")))
(cons "plaid magenta" (list (cons 5 "striped red") (cons 4 "striped salmon")))
(cons "shiny blue" (list (cons 2 "shiny turquoise") (cons 1 "posh orange")))
(cons "faded aqua" (list (cons 3 "light yellow") (cons 3 "wavy purple") (cons 5 "dull lime") (cons 5 "dotted black")))
(cons "mirrored blue" (list (cons 5 "wavy silver")))
(cons "posh indigo" (list (cons 5 "dark tan") (cons 2 "vibrant blue") (cons 5 "dark bronze") (cons 2 "vibrant crimson")))
(cons "clear plum" (list (cons 1 "wavy teal") (cons 1 "faded yellow")))
(cons "dark gray" (list (cons 4 "bright lavender")))
(cons "muted coral" (list (cons 4 "shiny red") (cons 2 "pale teal") (cons 4 "dim olive") (cons 3 "muted silver")))
(cons "dim gold" (list (cons 2 "pale gold") (cons 3 "vibrant red")))
(cons "plaid violet" (list (cons 3 "faded green") (cons 4 "mirrored teal") (cons 1 "wavy purple") (cons 1 "faded yellow")))
(cons "clear tomato" (list (cons 2 "drab beige") (cons 3 "dim cyan")))
(cons "bright beige" (list (cons 5 "muted brown") (cons 4 "wavy red") (cons 4 "clear maroon")))
(cons "wavy teal" (list (cons 4 "muted beige") (cons 1 "posh salmon") (cons 2 "posh black") (cons 2 "dotted maroon")))
(cons "vibrant salmon" (list (cons 4 "vibrant purple") (cons 4 "dull chartreuse")))
(cons "dull coral" (list (cons 2 "light red") (cons 3 "dark plum") (cons 3 "bright gray") (cons 1 "dotted cyan")))
(cons "bright turquoise" (list (cons 4 "plaid teal") (cons 3 "muted orange")))
(cons "wavy maroon" (list (cons 5 "pale fuchsia") (cons 5 "dotted magenta")))
(cons "plaid gold" (list (cons 2 "shiny lavender") (cons 1 "vibrant gray") (cons 5 "mirrored teal")))
(cons "wavy black" (list (cons 1 "wavy magenta")))
(cons "drab beige" (list (cons 1 "mirrored chartreuse") (cons 3 "wavy brown") (cons 4 "pale beige") (cons 2 "pale turquoise")))
(cons "posh blue" (list (cons 4 "clear silver")))
(cons "vibrant turquoise" (list (cons 1 "posh white") (cons 2 "bright gold")))
(cons "faded black" (list (cons 5 "wavy black") (cons 1 "shiny crimson")))
(cons "pale salmon" (list (cons 1 "vibrant brown")))
(cons "striped gray" (list (cons 1 "mirrored violet") (cons 4 "dull violet") (cons 4 "muted turquoise")))
(cons "light brown" (list (cons 5 "muted crimson") (cons 1 "drab crimson") (cons 4 "muted aqua") (cons 5 "dotted blue")))
(cons "striped turquoise" (list (cons 5 "muted blue") (cons 4 "mirrored salmon")))
(cons "shiny lime" (list (cons 1 "vibrant purple") (cons 4 "pale turquoise") (cons 4 "drab tomato") (cons 4 "dotted maroon")))
(cons "dotted white" (list (cons 5 "pale violet") (cons 1 "posh plum") (cons 1 "shiny chartreuse") (cons 2 "faded bronze")))
(cons "dotted crimson" (list (cons 2 "shiny olive") (cons 2 "mirrored yellow")))
(cons "mirrored teal" (list (cons 1 "dull violet") (cons 4 "shiny red") (cons 3 "drab black") (cons 1 "posh magenta")))
(cons "striped lavender" (list (cons 4 "light crimson")))
(cons "pale chartreuse" (list (cons 1 "wavy red")))
(cons "posh gray" (list (cons 3 "posh black")))
(cons "clear teal" (list (cons 4 "dull violet") (cons 4 "dotted chartreuse") (cons 3 "drab tan")))
(cons "light olive" (list (cons 3 "muted olive") (cons 4 "plaid turquoise")))
(cons "light tomato" (list (cons 5 "dull chartreuse") (cons 3 "muted beige")))
(cons "light orange" (list (cons 2 "wavy lavender")))
(cons "wavy coral" (list (cons 5 "drab beige") (cons 4 "plaid white")))
(cons "dotted violet" (list (cons 5 "muted salmon") (cons 5 "shiny red") (cons 3 "shiny crimson")))
(cons "muted fuchsia" (list (cons 5 "dull coral")))
(cons "pale turquoise" (list (cons 3 "vibrant red")))
(cons "faded beige" (list (cons 2 "striped magenta")))
(cons "dull tan" (list (cons 3 "drab maroon") (cons 3 "muted beige")))
(cons "posh lime" (list (cons 4 "wavy turquoise") (cons 2 "light blue") (cons 1 "posh salmon")))
(cons "drab magenta" (list (cons 5 "dim magenta")))
(cons "striped crimson" (list (cons 1 "dull white") (cons 4 "muted plum") (cons 1 "posh chartreuse")))
(cons "vibrant maroon" (list (cons 4 "pale aqua")))
(cons "dotted black" (list (cons 5 "shiny bronze") (cons 1 "shiny lime") (cons 5 "dotted yellow") (cons 1 "wavy turquoise")))
(cons "wavy aqua" (list (cons 3 "dull tomato") (cons 1 "shiny olive") (cons 4 "vibrant brown") (cons 2 "dim chartreuse")))
(cons "dim tan" (list (cons 2 "bright plum") (cons 4 "striped gold") (cons 4 "dull coral")))
(cons "dull fuchsia" (list (cons 5 "wavy maroon")))
(cons "striped red" (list (cons 5 "shiny red") (cons 4 "clear gold") (cons 4 "posh magenta") (cons 2 "bright yellow")))
(cons "dotted lavender" (list (cons 3 "faded lavender")))
(cons "muted turquoise" (list (cons 4 "faded fuchsia")))
(cons "bright gray" (list (cons 2 "light silver") (cons 3 "dull violet")))
(cons "dull indigo" (list (cons 2 "dim violet") (cons 3 "plaid salmon") (cons 5 "plaid beige")))
(cons "wavy purple" (list (cons 3 "dim yellow") (cons 1 "posh salmon")))
(cons "wavy lime" (list (cons 2 "dark fuchsia") (cons 3 "dark salmon") (cons 5 "bright silver") (cons 5 "pale aqua")))
(cons "light cyan" (list (cons 2 "clear blue")))
(cons "light beige" (list (cons 5 "dull red") (cons 3 "dark violet") (cons 5 "shiny lime")))
(cons "mirrored silver" (list (cons 1 "plaid beige") (cons 5 "dull coral")))
(cons "dark beige" (list (cons 1 "clear tan") (cons 4 "wavy orange") (cons 3 "shiny cyan") (cons 5 "shiny magenta")))
(cons "vibrant crimson" (list (cons 2 "mirrored teal") (cons 3 "pale turquoise") (cons 5 "posh magenta")))
(cons "faded red" (list (cons 3 "plaid lime") (cons 2 "clear brown")))
(cons "dim bronze" (list (cons 2 "dark beige") (cons 1 "plaid cyan") (cons 3 "clear purple")))
(cons "bright maroon" (list (cons 3 "light gray") (cons 2 "faded turquoise") (cons 1 "posh cyan")))
(cons "clear gray" (list (cons 4 "faded green")))
(cons "pale silver" (list (cons 3 "dull magenta")))
(cons "dotted red" (list (cons 2 "clear purple") (cons 1 "faded crimson") (cons 5 "dull bronze") (cons 5 "muted plum")))
(cons "striped maroon" (list (cons 5 "mirrored cyan") (cons 3 "dark green") (cons 4 "clear indigo") (cons 2 "muted beige")))
(cons "dark cyan" (list (cons 3 "dotted maroon") (cons 2 "vibrant red")))
(cons "clear bronze" (list (cons 1 "drab lime") (cons 5 "light gold")))
(cons "dull yellow" (list (cons 1 "dull chartreuse") (cons 1 "muted olive")))
(cons "plaid lavender" (list (cons 1 "vibrant silver") (cons 5 "clear fuchsia")))
(cons "posh black" (list (cons 5 "dotted salmon") (cons 4 "drab tomato") (cons 5 "drab black")))
(cons "faded lime" (list (cons 1 "dark silver")))
(cons "clear lavender" (list (cons 5 "light violet")))
(cons "dotted gray" (list (cons 4 "clear lavender") (cons 3 "shiny magenta")))
(cons "shiny gray" (list (cons 5 "dull brown")))
(cons "drab coral" (list (cons 2 "faded beige")))
(cons "dark teal" (list (cons 3 "drab indigo") (cons 2 "light aqua") (cons 1 "faded tan") (cons 2 "wavy brown")))
(cons "shiny violet" (list (cons 1 "posh black") (cons 5 "dim beige")))
(cons "clear salmon" (list (cons 5 "clear orange")))
(cons "shiny olive" (list (cons 2 "shiny yellow") (cons 1 "shiny indigo") (cons 4 "bright yellow")))
(cons "plaid salmon" (list (cons 4 "striped yellow") (cons 4 "mirrored chartreuse") (cons 3 "light magenta") (cons 2 "mirrored magenta")))
(cons "wavy orange" (list (cons 5 "vibrant purple")))
(cons "posh magenta" (list (cons 3 "mirrored chartreuse") (cons 4 "vibrant red")))
(cons "pale fuchsia" (list (cons 5 "muted silver")))
(cons "light black" (list (cons 5 "wavy orange") (cons 5 "faded tomato")))
(cons "light gold" (list (cons 1 "dull red")))
(cons "bright brown" (list (cons 5 "mirrored beige") (cons 5 "faded indigo")))
(cons "muted teal" (list (cons 5 "posh magenta") (cons 1 "dim gray") (cons 3 "pale plum")))
(cons "pale plum" (list (cons 2 "muted beige") (cons 2 "posh magenta") (cons 2 "shiny gold")))
(cons "drab gold" (list (cons 1 "striped beige")))
(cons "posh gold" (list (cons 3 "shiny silver")))
(cons "dull turquoise" (list (cons 4 "vibrant crimson") (cons 3 "faded gray") (cons 5 "muted purple")))
(cons "light chartreuse" (list (cons 2 "bright lavender") (cons 4 "bright silver")))
(cons "striped chartreuse" (list (cons 1 "shiny coral") (cons 2 "clear blue") (cons 2 "dotted turquoise")))
(cons "dark aqua" (list (cons 3 "wavy bronze") (cons 4 "shiny brown") (cons 2 "bright violet") (cons 1 "dotted indigo")))
(cons "muted bronze" (list (cons 3 "pale salmon") (cons 1 "striped teal")))
(cons "dark violet" (list (cons 2 "wavy magenta")))
(cons "dark maroon" (list (cons 2 "muted red")))
(cons "shiny silver" (list (cons 2 "light gray") (cons 1 "pale aqua") (cons 5 "dim tomato")))
(cons "bright lavender" (list (cons 5 "striped red") (cons 3 "faded tan")))
(cons "dim olive" (list (cons 3 "posh cyan") (cons 4 "light aqua") (cons 1 "wavy tan") (cons 3 "dull silver")))
(cons "posh beige" (list (cons 5 "faded tan") (cons 1 "shiny lime") (cons 4 "wavy lavender")))
(cons "muted maroon" (list (cons 3 "mirrored purple") (cons 2 "mirrored gold") (cons 1 "clear tan")))
(cons "vibrant yellow" (list (cons 4 "light lavender")))
(cons "light purple" (list (cons 1 "faded olive") (cons 1 "wavy red")))
(cons "bright yellow" (list (cons 3 "dotted salmon") (cons 4 "posh magenta") (cons 4 "striped salmon")))
(cons "dull gray" (list (cons 5 "posh magenta") (cons 1 "shiny white") (cons 2 "dim bronze") (cons 2 "dim lavender")))
(cons "vibrant plum" (list (cons 1 "faded tan") (cons 2 "pale turquoise") (cons 4 "bright chartreuse") (cons 4 "dull violet")))
(cons "posh chartreuse" (list (cons 1 "bright chartreuse") (cons 4 "drab black") (cons 2 "posh magenta") (cons 4 "dark orange")))
(cons "drab gray" (list (cons 4 "plaid turquoise")))
(cons "dark brown" (list (cons 4 "dotted green") (cons 3 "dim lavender")))
(cons "mirrored crimson" (list (cons 2 "light teal") (cons 2 "plaid blue") (cons 5 "wavy red") (cons 2 "bright tomato")))
(cons "dotted gold" (list (cons 4 "bright olive")))
(cons "dark salmon" (list (cons 3 "pale turquoise") (cons 5 "faded tan") (cons 1 "mirrored chartreuse")))
(cons "wavy gray" (list (cons 4 "shiny green") (cons 5 "shiny red")))
(cons "dotted blue" (list (cons 2 "wavy yellow") (cons 1 "dull beige")))
(cons "dim maroon" (list (cons 2 "wavy maroon") (cons 5 "dim violet") (cons 4 "dark tan")))
(cons "plaid purple" (list (cons 2 "dark teal") (cons 2 "mirrored black") (cons 1 "wavy lavender")))
(cons "dull blue" (list (cons 1 "bright gold") (cons 2 "dim olive") (cons 4 "muted chartreuse") (cons 2 "striped salmon")))
(cons "muted white" (list (cons 4 "light bronze") (cons 3 "wavy beige")))
(cons "muted gold" '())
(cons "drab green" (list (cons 2 "plaid chartreuse")))
(cons "clear coral" (list (cons 5 "mirrored cyan")))
(cons "drab turquoise" (list (cons 3 "posh black")))
(cons "dotted fuchsia" (list (cons 2 "light red") (cons 4 "clear aqua") (cons 1 "posh magenta") (cons 4 "vibrant cyan")))
(cons "clear lime" (list (cons 3 "dark chartreuse")))
(cons "mirrored plum" (list (cons 1 "wavy tan") (cons 2 "bright olive")))
(cons "vibrant coral" (list (cons 3 "light gray") (cons 5 "light white")))
(cons "pale bronze" (list (cons 2 "bright silver") (cons 5 "vibrant tan") (cons 4 "posh lime") (cons 3 "wavy silver")))
(cons "plaid blue" (list (cons 4 "dotted beige") (cons 2 "wavy olive") (cons 2 "striped tomato")))
(cons "shiny teal" (list (cons 2 "shiny violet") (cons 1 "faded blue") (cons 5 "shiny white") (cons 4 "dim fuchsia")))
(cons "clear black" (list (cons 4 "faded purple") (cons 1 "dim tomato") (cons 5 "striped brown") (cons 2 "faded indigo")))
(cons "clear orange" (list (cons 2 "bright gold") (cons 5 "light crimson") (cons 2 "faded yellow")))
(cons "drab maroon" (list (cons 1 "vibrant red") (cons 2 "dotted bronze")))
(cons "drab blue" (list (cons 1 "mirrored aqua") (cons 1 "dark gold") (cons 3 "shiny crimson")))
(cons "striped black" (list (cons 2 "drab black") (cons 5 "dark orange")))
(cons "light lavender" (list (cons 1 "clear blue") (cons 1 "striped red")))
(cons "posh bronze" (list (cons 5 "light red") (cons 4 "dull plum") (cons 1 "dim coral") (cons 3 "clear blue")))
(cons "plaid beige" (list (cons 5 "dotted turquoise") (cons 2 "light cyan")))
(cons "plaid fuchsia" (list (cons 3 "wavy fuchsia")))
(cons "shiny bronze" (list (cons 5 "vibrant silver") (cons 3 "striped silver") (cons 3 "pale turquoise") (cons 2 "faded olive")))
(cons "vibrant purple" (list (cons 3 "wavy magenta")))
(cons "pale magenta" (list (cons 4 "dim yellow") (cons 1 "dim aqua")))
(cons "faded purple" (list (cons 5 "mirrored black") (cons 1 "muted beige") (cons 1 "muted aqua") (cons 1 "light maroon")))
(cons "light turquoise" (list (cons 5 "muted brown") (cons 1 "posh beige") (cons 2 "vibrant fuchsia") (cons 3 "faded teal")))
(cons "vibrant lavender" (list (cons 1 "light chartreuse") (cons 3 "mirrored teal") (cons 5 "drab lavender") (cons 4 "shiny brown")))
(cons "striped yellow" (list (cons 1 "dotted cyan") (cons 3 "mirrored turquoise")))
(cons "drab bronze" (list (cons 3 "shiny lavender") (cons 5 "muted yellow") (cons 3 "plaid teal") (cons 2 "plaid gold")))
(cons "posh maroon" (list (cons 5 "bright fuchsia") (cons 3 "dotted indigo") (cons 5 "dark teal") (cons 1 "faded violet")))
(cons "vibrant cyan" (list (cons 2 "dark orange")))
(cons "striped aqua" (list (cons 2 "light bronze") (cons 1 "dull beige") (cons 4 "pale violet") (cons 5 "pale beige")))
(cons "faded gold" (list (cons 4 "pale crimson")))
(cons "muted olive" (list (cons 2 "mirrored teal") (cons 1 "dim aqua") (cons 3 "posh chartreuse") (cons 3 "dull brown")))
(cons "dim coral" (list (cons 1 "mirrored gold")))
(cons "dull silver" (list (cons 5 "faded gray") (cons 5 "light red") (cons 3 "light crimson") (cons 4 "bright chartreuse")))
(cons "vibrant gray" (list (cons 2 "plaid silver") (cons 5 "plaid violet") (cons 1 "dim silver") (cons 4 "mirrored chartreuse")))
(cons "plaid crimson" (list (cons 2 "vibrant bronze") (cons 1 "drab olive") (cons 1 "pale purple")))
(cons "dotted maroon" '())
(cons "vibrant brown" (list (cons 2 "dull violet") (cons 4 "muted beige") (cons 4 "wavy teal")))
(cons "bright tomato" (list (cons 3 "muted beige")))
(cons "shiny cyan" (list (cons 5 "clear gold") (cons 2 "shiny lime") (cons 4 "wavy magenta") (cons 2 "wavy lavender")))
(cons "drab tan" (list (cons 1 "plaid red")))
(cons "dull plum" (list (cons 4 "dotted magenta") (cons 1 "plaid silver") (cons 1 "pale teal") (cons 1 "dim yellow")))
(cons "clear gold" (list (cons 1 "bright gold") (cons 4 "dark orange") (cons 4 "posh magenta")))
(cons "shiny gold" (list (cons 5 "dark salmon") (cons 2 "wavy purple") (cons 5 "dark cyan") (cons 5 "dull chartreuse")))
(cons "mirrored tomato" (list (cons 3 "light aqua") (cons 4 "pale plum") (cons 1 "pale beige")))
(cons "dim tomato" (list (cons 5 "light crimson") (cons 2 "bright lavender")))
(cons "mirrored tan" (list (cons 1 "vibrant plum") (cons 2 "faded violet") (cons 5 "striped lime") (cons 3 "muted white")))
(cons "faded teal" (list (cons 1 "drab silver")))
(cons "dim red" (list (cons 2 "clear turquoise") (cons 3 "drab maroon")))
(cons "dark magenta" (list (cons 2 "clear cyan")))
(cons "vibrant gold" (list (cons 4 "dotted salmon") (cons 3 "bright chartreuse") (cons 3 "striped purple")))
(cons "muted brown" (list (cons 4 "posh beige") (cons 3 "muted aqua") (cons 5 "dim beige") (cons 4 "dim magenta")))
(cons "plaid orange" (list (cons 2 "dark purple") (cons 4 "mirrored tomato") (cons 1 "vibrant orange")))
(cons "pale gold" (list (cons 1 "vibrant plum") (cons 4 "dotted violet")))
(cons "plaid gray" (list (cons 3 "bright silver") (cons 5 "drab fuchsia")))
(cons "muted orange" (list (cons 5 "dull magenta") (cons 5 "clear lavender") (cons 4 "mirrored chartreuse") (cons 4 "vibrant silver")))
(cons "muted aqua" (list (cons 2 "dim silver") (cons 2 "wavy black")))
(cons "dim crimson" (list (cons 2 "mirrored bronze") (cons 4 "muted cyan")))
(cons "dark tomato" (list (cons 5 "pale blue")))
(cons "bright salmon" (list (cons 1 "vibrant tan") (cons 4 "bright white") (cons 1 "dim gray")))
(cons "mirrored orange" (list (cons 1 "dark salmon") (cons 5 "drab beige") (cons 5 "dull chartreuse") (cons 1 "shiny cyan")))
(cons "clear aqua" (list (cons 2 "dim teal") (cons 4 "wavy olive")))
(cons "bright bronze" (list (cons 3 "shiny maroon")))
(cons "vibrant black" (list (cons 3 "muted gold") (cons 2 "striped red") (cons 2 "pale magenta") (cons 4 "clear violet")))
(cons "clear yellow" (list (cons 2 "plaid maroon")))
(cons "pale lavender" (list (cons 1 "shiny maroon") (cons 5 "bright cyan") (cons 5 "shiny orange") (cons 4 "striped tomato")))
(cons "dark chartreuse" (list (cons 2 "wavy brown")))
(cons "mirrored violet" (list (cons 2 "light lavender") (cons 4 "dull coral") (cons 2 "light red")))
(cons "vibrant beige" (list (cons 2 "shiny red") (cons 2 "clear tan")))
(cons "mirrored coral" (list (cons 4 "faded coral") (cons 2 "dull bronze")))
(cons "posh red" (list (cons 4 "wavy brown") (cons 1 "dark salmon") (cons 5 "dull chartreuse") (cons 5 "vibrant crimson")))
(cons "light green" (list (cons 4 "posh fuchsia")))
(cons "wavy green" (list (cons 3 "dark green") (cons 4 "posh chartreuse") (cons 1 "mirrored black")))
(cons "drab violet" (list (cons 5 "wavy yellow")))
(cons "dark crimson" (list (cons 1 "bright gray") (cons 2 "shiny violet") (cons 3 "pale chartreuse")))
(cons "posh green" (list (cons 2 "bright yellow") (cons 2 "faded yellow")))
(cons "shiny plum" (list (cons 3 "shiny indigo") (cons 1 "dark gold") (cons 2 "dim coral")))
(cons "striped beige" (list (cons 2 "muted beige")))
(cons "dark orange" (list (cons 5 "bright gold") (cons 2 "dotted maroon") (cons 1 "striped salmon") (cons 3 "vibrant red")))
(cons "bright orange" (list (cons 4 "muted blue") (cons 5 "striped blue") (cons 4 "dark cyan")))
(cons "dark black" (list (cons 1 "shiny lime") (cons 1 "clear olive") (cons 4 "dull bronze") (cons 3 "muted lavender")))
(cons "pale orange" (list (cons 3 "plaid violet") (cons 1 "shiny red") (cons 1 "dull coral") (cons 1 "shiny bronze")))
(cons "mirrored salmon" (list (cons 4 "vibrant red") (cons 3 "muted beige") (cons 2 "dark orange")))
(cons "drab yellow" (list (cons 1 "bright white")))
(cons "dull tomato" (list (cons 4 "muted beige") (cons 3 "posh salmon") (cons 2 "shiny maroon")))
(cons "striped fuchsia" (list (cons 5 "pale beige") (cons 3 "mirrored gray")))
(cons "mirrored beige" (list (cons 5 "mirrored black") (cons 2 "dim lavender") (cons 1 "clear lime")))
(cons "wavy tomato" (list (cons 4 "wavy fuchsia")))
(cons "bright indigo" (list (cons 2 "dull violet") (cons 5 "dull green") (cons 3 "dotted cyan") (cons 2 "dotted tan")))
(cons "striped blue" (list (cons 1 "posh red") (cons 4 "bright fuchsia") (cons 4 "dark aqua")))
(cons "bright green" (list (cons 3 "dim violet") (cons 2 "shiny coral") (cons 1 "dim white") (cons 4 "dim yellow")))
(cons "dotted salmon" (list (cons 5 "dull red") (cons 2 "striped salmon") (cons 5 "dotted maroon") (cons 3 "shiny red")))
(cons "light magenta" (list (cons 1 "dark fuchsia") (cons 1 "pale turquoise") (cons 5 "pale plum") (cons 3 "vibrant tan")))
(cons "mirrored olive" (list (cons 1 "shiny lavender")))
(cons "dark coral" (list (cons 3 "wavy teal") (cons 4 "muted plum")))
(cons "posh teal" (list (cons 1 "pale violet") (cons 5 "muted tan") (cons 1 "drab gray") (cons 2 "drab beige")))
(cons "bright teal" (list (cons 5 "mirrored coral")))
(cons "striped orange" (list (cons 3 "clear olive")))
(cons "faded plum" (list (cons 5 "striped black") (cons 1 "striped gold")))
(cons "plaid tomato" (list (cons 1 "muted salmon") (cons 2 "pale violet") (cons 1 "light violet") (cons 3 "dim tomato")))
(cons "dim blue" (list (cons 4 "drab salmon") (cons 4 "faded plum") (cons 1 "light salmon") (cons 3 "dark turquoise")))
(cons "striped coral" (list (cons 3 "wavy fuchsia")))
(cons "light violet" (list (cons 4 "dim beige") (cons 4 "striped lavender") (cons 1 "dotted orange") (cons 1 "wavy purple")))
(cons "dull white" (list (cons 2 "faded purple") (cons 1 "bright silver") (cons 4 "pale bronze") (cons 3 "clear fuchsia")))
(cons "dim white" (list (cons 2 "light yellow") (cons 5 "posh gold") (cons 1 "bright blue") (cons 1 "striped chartreuse")))
(cons "bright chartreuse" (list (cons 1 "muted gold") (cons 1 "dotted maroon")))
(cons "striped purple" (list (cons 2 "light orange") (cons 1 "dotted maroon") (cons 3 "dim magenta") (cons 4 "plaid violet")))
(cons "dotted tomato" (list (cons 5 "posh chartreuse")))
(cons "wavy lavender" (list (cons 4 "dim yellow") (cons 4 "pale turquoise") (cons 4 "vibrant red") (cons 3 "bright yellow")))
(cons "striped teal" (list (cons 2 "bright yellow")))
(cons "drab crimson" (list (cons 1 "wavy tan") (cons 1 "dull green") (cons 3 "muted blue")))
(cons "dull lime" (list (cons 3 "shiny tomato")))
(cons "posh salmon" '())
(cons "vibrant aqua" (list (cons 2 "shiny indigo") (cons 3 "shiny crimson") (cons 4 "shiny cyan")))
(cons "drab black" (list (cons 3 "dull violet") (cons 4 "dotted maroon") (cons 3 "vibrant purple") (cons 3 "muted plum")))
(cons "drab olive" (list (cons 5 "drab orange") (cons 4 "dotted green") (cons 5 "drab chartreuse")))
(cons "dark plum" (list (cons 2 "dotted salmon") (cons 5 "wavy magenta") (cons 1 "bright chartreuse")))
(cons "plaid brown" (list (cons 2 "light lavender")))
(cons "striped magenta" (list (cons 5 "pale lime") (cons 4 "posh salmon") (cons 5 "clear tomato") (cons 5 "dull plum")))
(cons "dull orange" (list (cons 4 "light maroon")))
(cons "vibrant orange" (list (cons 5 "dull red") (cons 1 "posh chartreuse")))
(cons "mirrored turquoise" (list (cons 4 "drab cyan") (cons 1 "posh cyan") (cons 4 "clear gold") (cons 5 "plaid magenta")))
(cons "mirrored black" '())
(cons "shiny black" (list (cons 5 "dotted green") (cons 1 "dim violet") (cons 1 "clear cyan") (cons 2 "muted fuchsia")))
(cons "vibrant indigo" (list (cons 1 "light maroon")))
(cons "bright fuchsia" (list (cons 5 "faded olive")))
(cons "dotted plum" (list (cons 5 "shiny violet")))
(cons "plaid lime" (list (cons 2 "bright gray") (cons 4 "pale beige") (cons 4 "light silver")))
(cons "plaid red" (list (cons 1 "shiny maroon") (cons 4 "striped lavender") (cons 5 "mirrored purple")))
(cons "mirrored lime" (list (cons 5 "faded coral") (cons 3 "dark gold") (cons 5 "mirrored indigo") (cons 5 "dull coral")))
(cons "drab lime" (list (cons 2 "dotted aqua") (cons 5 "shiny chartreuse")))
(cons "faded tan" (list (cons 1 "muted plum") (cons 1 "posh salmon")))
(cons "dark silver" (list (cons 4 "dotted maroon") (cons 4 "shiny white")))
(cons "striped indigo" (list (cons 5 "dull plum") (cons 2 "light lavender") (cons 3 "light red") (cons 1 "muted olive")))
(cons "bright gold" '())
(cons "plaid black" (list (cons 2 "dull violet") (cons 5 "muted olive") (cons 1 "muted teal")))
(cons "dotted chartreuse" '())
(cons "vibrant blue" (list (cons 1 "shiny cyan")))
(cons "dim indigo" (list (cons 1 "bright purple") (cons 1 "plaid magenta") (cons 5 "posh fuchsia") (cons 5 "plaid red")))
(cons "light red" (list (cons 5 "bright gold") (cons 4 "plaid silver") (cons 1 "dull violet") (cons 4 "pale turquoise")))
(cons "dim black" (list (cons 3 "dim orange") (cons 5 "dull lime") (cons 2 "faded indigo") (cons 3 "dotted olive")))
(cons "mirrored gold" (list (cons 2 "muted gold") (cons 5 "dark cyan")))
(cons "posh aqua" (list (cons 1 "clear violet")))
(cons "light blue" (list (cons 3 "drab chartreuse") (cons 2 "dull chartreuse")))
(cons "shiny maroon" (list (cons 1 "wavy violet")))
(cons "faded lavender" (list (cons 1 "dark salmon") (cons 5 "vibrant orange") (cons 3 "vibrant purple") (cons 5 "posh black")))
(cons "faded olive" (list (cons 2 "mirrored teal") (cons 5 "pale plum") (cons 4 "pale brown")))
(cons "drab indigo" (list (cons 1 "dim cyan") (cons 1 "plaid silver")))
(cons "clear white" (list (cons 4 "posh beige")))
(cons "wavy violet" (list (cons 5 "dotted fuchsia")))
(cons "dark turquoise" (list (cons 5 "vibrant turquoise") (cons 3 "vibrant lavender")))
(cons "striped violet" (list (cons 5 "mirrored turquoise") (cons 1 "muted orange") (cons 3 "dim teal") (cons 4 "posh green")))
(cons "wavy yellow" (list (cons 2 "dim yellow") (cons 5 "dim lavender")))
(cons "dark red" (list (cons 4 "striped gold") (cons 3 "vibrant tomato")))
(cons "plaid maroon" (list (cons 5 "light white") (cons 5 "plaid black")))
(cons "bright black" (list (cons 3 "light maroon") (cons 5 "shiny lime") (cons 2 "vibrant maroon") (cons 3 "clear violet")))
(cons "drab salmon" (list (cons 2 "clear coral") (cons 4 "dark indigo")))
(cons "plaid green" (list (cons 2 "pale indigo")))
(cons "pale teal" (list (cons 4 "drab black") (cons 3 "faded gray") (cons 5 "posh beige") (cons 4 "faded yellow")))
(cons "light silver" (list (cons 5 "bright yellow") (cons 1 "dim silver") (cons 5 "posh chartreuse")))
(cons "dull magenta" (list (cons 3 "posh turquoise") (cons 3 "light magenta") (cons 4 "shiny orange") (cons 4 "clear turquoise")))
(cons "pale white" (list (cons 5 "dark cyan")))
(cons "dull chartreuse" (list (cons 3 "mirrored black") (cons 3 "dotted salmon") (cons 5 "pale turquoise")))
(cons "dim salmon" (list (cons 2 "mirrored yellow") (cons 5 "striped salmon") (cons 1 "drab tomato") (cons 5 "dull yellow")))
(cons "shiny crimson" (list (cons 5 "faded tan") (cons 2 "muted salmon") (cons 1 "wavy teal") (cons 3 "vibrant orange")))
(cons "dark purple" (list (cons 2 "muted plum") (cons 5 "bright lavender") (cons 1 "dark cyan") (cons 4 "clear orange")))
(cons "clear brown" (list (cons 2 "dim orange") (cons 1 "vibrant maroon") (cons 2 "striped lime")))
(cons "muted silver" (list (cons 5 "vibrant gray")))
(cons "vibrant bronze" (list (cons 3 "posh red")))
(cons "mirrored maroon" (list (cons 3 "clear magenta") (cons 2 "posh brown") (cons 5 "wavy teal")))
(cons "muted tomato" (list (cons 5 "faded aqua") (cons 4 "wavy lavender") (cons 1 "mirrored silver")))
(cons "posh olive" (list (cons 4 "faded salmon") (cons 1 "muted green") (cons 5 "light tomato") (cons 3 "dark gold")))
(cons "dotted turquoise" (list (cons 5 "light orange") (cons 1 "dull brown")))
(cons "light bronze" (list (cons 2 "pale cyan") (cons 3 "shiny lime") (cons 2 "faded olive")))
(cons "striped gold" (list (cons 4 "muted salmon") (cons 1 "bright yellow") (cons 1 "dark plum") (cons 4 "light maroon")))
(cons "faded maroon" (list (cons 5 "wavy silver") (cons 3 "plaid magenta")))
(cons "clear magenta" (list (cons 2 "wavy turquoise")))
(cons "vibrant olive" (list (cons 1 "muted silver")))
(cons "clear tan" (list (cons 4 "mirrored gold")))
(cons "posh orange" (list (cons 3 "plaid blue") (cons 4 "dotted aqua")))
(cons "wavy cyan" (list (cons 3 "posh lavender")))
(cons "shiny chartreuse" (list (cons 5 "mirrored cyan") (cons 3 "posh chartreuse") (cons 4 "dotted aqua")))
(cons "light lime" (list (cons 5 "muted plum") (cons 2 "wavy purple")))
(cons "wavy silver" (list (cons 4 "faded lavender")))
(cons "drab red" (list (cons 4 "clear tomato") (cons 4 "pale turquoise") (cons 2 "dull yellow")))
(cons "light aqua" (list (cons 3 "dotted aqua")))
(cons "dim purple" (list (cons 2 "striped gold") (cons 2 "drab tan") (cons 2 "mirrored tan")))
(cons "shiny indigo" (list (cons 1 "pale magenta") (cons 5 "dim plum") (cons 3 "muted blue") (cons 4 "dim coral")))
(cons "pale lime" (list (cons 2 "mirrored cyan") (cons 4 "dull violet") (cons 1 "striped lime")))
(cons "posh lavender" (list (cons 5 "clear purple") (cons 2 "muted gold") (cons 5 "dull brown") (cons 4 "muted lime")))
(cons "dull lavender" (list (cons 1 "striped violet") (cons 3 "muted bronze")))
(cons "dotted lime" (list (cons 3 "plaid magenta") (cons 5 "plaid violet") (cons 1 "shiny lime") (cons 3 "plaid purple")))
(cons "posh coral" (list (cons 5 "mirrored violet") (cons 1 "clear violet") (cons 1 "dark fuchsia") (cons 3 "dotted silver")))
(cons "bright plum" (list (cons 5 "wavy brown")))
(cons "pale coral" (list (cons 3 "bright olive")))
(cons "dim fuchsia" (list (cons 2 "bright chartreuse") (cons 4 "mirrored teal") (cons 4 "posh salmon") (cons 3 "light chartreuse")))
(cons "dim cyan" (list (cons 2 "faded tan") (cons 4 "mirrored gold")))
(cons "faded cyan" (list (cons 1 "dotted black") (cons 1 "shiny maroon") (cons 2 "muted chartreuse")))
))

(define (can-contain? bag) (let
  (
    (data (assoc bag input))
    (found? #f)
  )
  
  (if data (begin
    (for-each
      (lambda (bag-pair) (let
        (
          (count (car bag-pair))
          (name (cdr bag-pair))
        )
        
        (if (not found?)
          (if (string=? name "shiny gold")
            (set! found? #t)
            (if (> count 0)
              (set! found? (can-contain? name))
            )
          )
        )
      ))
      (cdr data)
    )
    
    (if found?
      (set-cdr! data (list (cons 1 "shiny gold")))
      (set-cdr! data '())
    )
  ))
  
  found?
))

(define total 0)

(for-each
  (lambda (bag)
    (if (can-contain? bag)
      (set! total (1+ total))
    )
  )
  (map car input)
)

(pp total)
